version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "reluna-team"
    assignees:
      - "reluna-team"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      storybook:
        patterns:
          - "@storybook/*"
      testing:
        patterns:
          - "@testing-library/*"
          - "vitest*"
          - "jest*"
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*" 